terraform-ibm-modules/terraform-ibm-observability-instances

- README.md
- module-metadata.json
- variables.tf
Readme and variable description updates to align with IBM Cloud docs
**Check the relevant boxes:**
- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).
> docs: readme and variable description updates

- README.md
- main.tf
- module-metadata.json
- outputs.tf
- variables.tf
Added support for the service endpoints
Address issue https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/issues/30
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> feat: added support to set service endpoints

- README.md
- main.tf
- module-metadata.json
- variables.tf
Pass the resource key role as a module input
https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/issues/206
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> feat: update resource key role

- examples/observability_archive/main.tf
- examples/observability_basic/main.tf
Updating the default value of the instance name in examples is set to ${var.prefix} which will create activity tracker, log analysis and IBM cloud monitoring with same name.
https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/issues/224
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for …
> fix: update default instance name

- .secrets.baseline
- README.md
- modules/activity_tracker/README.md
- modules/cloud_monitoring/README.md
- modules/log_analysis/README.md
Roll out new Overview hook in docs
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> Roll out new Overview hook in docs

- moved.tf
One of the internal resources is missing a moved block.
https://github.ibm.com/GoldenEye/issues/issues/5968
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> fix: added missing moved block

- .secrets.baseline
- README.md
- examples/observability_archive/version.tf
- examples/observability_at_event_routing/version.tf
- examples/observability_basic/version.tf
- module-metadata.json
- modules/activity_tracker/README.md
- modules/activity_tracker/version.tf
- modules/cloud_monitoring/README.md
- modules/cloud_monitoring/version.tf
- modules/log_analysis/README.md
- modules/log_analysis/version.tf
- version.tf
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> Update TF range to `>= 1.0.0, < 1.6.0`

- examples/observability_at_event_routing/variables.tf
- modules/activity_tracker/variables.tf
Update examples to support Madrid
Additional validation in the root module. This should have no impact to consumers, it simply causes the deploy to fail sooner IF/WHEN the list of permitted regions is invalid.
```
/run pipeline
```
- Use …
> fix: support for Madrid

- modules/activity_tracker/variables.tf
The current validation fails is you set `service_to_service_enabled` to `true` and `api_key` to `null` which is a valid use case
```
/run pipeline
```
> fix: fix validation bug for `cos_targets` variable

- README.md
- modules/activity_tracker/README.md
- modules/cloud_monitoring/README.md
> docs: fix module source inside module's README

- cra-config.yaml
- examples/observability_archive/catalogValidationValues.json.template
- examples/observability_archive/variables.tf
- examples/observability_archive/version.tf
- examples/observability_at_event_routing/catalogValidationValues.json.template
- examples/observability_at_event_routing/variables.tf
- examples/observability_at_event_routing/version.tf
- examples/observability_basic/catalogValidationValues.json.template
- examples/observability_basic/variables.tf
- examples/observability_basic/version.tf
> Terraform example code optimized

- .secrets.baseline
- modules/activity_tracker/README.md
- modules/activity_tracker/main.tf
- modules/activity_tracker/version.tf
https://github.ibm.com/GoldenEye/issues/issues/8221
```
/run pipeline
```
> fix: add time sleep for auth policy

- examples/observability_archive/main.tf
- examples/observability_archive/outputs.tf
- examples/observability_at_event_routing/main.tf
Bump COS to v8.1.8 in examples
```
/run pipeline
```
> fix: Bump COS to v8.1.8 in examples

- modules/activity_tracker/variables.tf
fix: allow more permitted_target_regions
```
/run pipeline
```
> fix: allow more permitted_target_regions

- examples/advanced/main.tf
Issue: https://github.ibm.com/GoldenEye/issues/issues/10244
skip auth policy creation for buckets in advanced example
```
/run pipeline
```
> fix: skip auth policy creation for buckets

- README.md
- examples/basic/outputs.tf
- modules/cloud_logs/README.md
- modules/cloud_logs/outputs.tf
- outputs.tf
Issue: https://github.ibm.com/GoldenEye/issues/issues/10697
This is a dependent PR for the solution mentioned in the issue.
Add new outputs cloud_logs_ingress_endpoint and cloud_logs_ingress_private_endpoint
```
/run pipeline
```
- Use …
> feat: add ingress endpoint output

- README.md
- examples/advanced/main.tf
- examples/advanced/providers.tf
- examples/basic/providers.tf
- outputs.tf
- tests/other_test.go
- tests/pr_test.go
In https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/pull/576 I added some logic to the outputs in the root level module for log analysis, however there was a knock on affect which was causing a cycle error:
`Cycle: provider[\"registry.terraform.io/logdna/logdna\"].ld, module.observability_instances.module.log_analysis.logdna_archive.archive_config, module.observability_instances.module.log_analysis (close), module.observability_instances.output.log_analysis_resource_key (expand)`
I was able to reproduce in the examples, and have updated the conditional logic in the outputs to fix the issue
Run the CI pipeline when the PR is ready …
> fix: fix cycle error

- modules/metrics_routing/README.md
- modules/metrics_routing/main.tf
- modules/metrics_routing/version.tf
Resolves: https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/issues/603
```
/run pipeline
```
> fix: add time_sleep

- examples/advanced/main.tf
It has been a while since all the PR pipelines passed for renovate.
This addresses one of the issues, in that it regularly hits the quota/limit for trial cloud monitoring instances. By running the examples with a graduate tier plan this should avoid the issue.
Note: Expecting upgrade test to fail, since main will deploy a `trial`, which will either fail (due to quota), or pass and then fail during upgrade since the plan is changing.
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the …
> tests: avoid trial limit

- examples/advanced/main.tf
- tests/pr_test.go
Tests are flaky due to interaction between each other. Serialize tests to make them more reliable.
Bump modules in advanced tests (excluding major release bumps).
```
/run pipeline
```
> tests: serialize tests, bump modules

- modules/cloud_logs/main.tf
Issue: https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/issues/621
```
/run pipeline
```
> fix: add support for viewer role for EN auth policy
